#!/usr/bin/env php
<?php
namespace PMStats;

$command_name = 'stats_lang';
$command_help = "{$command_name} - Get stats for all lang files in a folder\n" .
                "Usage: {$command_name} [path]\n\n" .
                "Example: {$command_name} ~/git/appstores\n";
$min_parameters = 1;
$missing_parameter = "This command needs more parameters, please check {$command_name} --help.\n";
require_once __DIR__ . '/../inc/cli_init.php';

// User provided variables
$cli_path = Utils::getCliParam(1, $argv, '');

$changesets = Utils::getChangesets($cli_path, 'en-US/');
$stats = Stats::getStats($cli_path . 'en-US/', $changesets, 'lang');
$overall_stats = Stats::getGeneralStats($stats);

echo "Total number of strings at the end of the period, number of words between parenthesis.\n";
foreach ($overall_stats as $year => $data) {
    echo "{$year}: {$data['total']} ({$data['total_w']}) total, "
         . "{$data['added']} ({$data['added_w']}) added, "
         . "{$data['removed']} ({$data['removed_w']}) removed.\n";
}
